services:
  db:
    image: postgres:16
    container_name: task4-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  # mailpit:
  #   image: axllent/mailpit:v1.23
  #   container_name: task4-mailpit
  #   restart: unless-stopped
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task4-web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=app_db;Username=app_user;Password=app_password
      DATA_PROTECTION_KEYS_PATH: /var/data/dpkeys
      Smtp__Host: smtp.gmail.com
      Smtp__Port: 587
      Smtp__Username: "for.experiments.2026@gmail.com"
      Smtp__Password: "tcdc iahs qqjx eoth"
      Smtp__FromEmail: for.experiments.2026@gmail.com
      Smtp__FromName: Task4
      Smtp__UseSsl: true
    ports:
      - "8080:8080"
    volumes:
      - dp-keys:/var/data/dpkeys

volumes:
  pg-data:
  dp-keys:
